# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

#sfGuard
sf_guard_signin:
  url:   /backend/login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /backend/logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_forgot_password:
  url: /backend/forgot_password
  param: { module: sfGuardForgotPassword, action: index }

# default rules
homepage:
  url:   /backend/
  param: { module: main, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
 url:   /backend/:module
 param: { action: index }

default:
  url:   /backend/:module/:action/*
