# Travis CI
# Configuration

language: php
php:
  - 5.3
mysql:
  adapter: mysql2
  database: lufy2
  username: travis
  encoding: utf8

before_script:
  - "sudo apt-get update"
  - "sudo apt-get install php5-common php5-fpm php5-gd php-apc"
  - echo "extension = apc.so" >> ~/.phpenv/versions/5.3/etc/php.ini
  - "mysql -e 'CREATE DATABASE lufy2;'"
  - "ln -s config/databases.yml.travis config/databases.yml"
script:
  - "./configure.sh"
  - "php symfony doctrine:build --all --no-confirmation --and-load"
after_script:
  - "php symfony test:all"

branches:
  only:
    - master
