<?php

/**
 * Block
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    lufy
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Block extends BaseBlock
{
  public function updatePosition(array $post)
  {
    $size = count($post);
    for($i=1; $i<=$size; $i++):
      $q = Doctrine_Query::create()
        ->update('block')
        ->where('id_block = ?', $post[$i][id])
        ->set('position ',$post[$i][position])
        ->execute();
    endfor;
  }
  
  public function setVisible($block_id)
  {
        Doctrine_Query::create()
                ->update('block')
                ->set('is_active', '?', '1')
                ->where('id_block = ' . $block_id)
                ->execute();
  }  
  
  public function setHidden($block_id)
  {
        Doctrine_Query::create()
                ->update('block')
                ->set('is_active', '?', '0')
                ->where('id_block = ' . $block_id)
                ->execute();
  }
}