<?php

/**
 * Commande
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    lufy
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Commande extends BaseCommande {

    public function __toString() {
        return $this->getIdCommande();
    }
    public function IsPaypal($id) {
        $p = Doctrine::getTable('payement')->findOneByCommandeId($id);
        return $p->getIsPaypal();
    }
    public function getTeam($tournament_slot_id){
        $q = Doctrine::getTable('tournamentSlot')->findOneByIdTournamentSlot($tournament_slot_id);
        $t = Doctrine::getTable('team')->findOneByIdTeam($q->getTeamId());
        return $t->getName();
    }
}