<?php

/**
 * Faq
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    lufy
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Faq extends BaseFaq
{
  public function updatePosition(array $post)
  {
    $size = count($post);
    for($i=1; $i<=$size; $i++):
      $q = Doctrine_Query::create()
        ->update('faq')
        ->where('id_faq = ?', $post[$i][id])
        ->set('position ',$post[$i][position])
        ->execute();
    endfor;
  }
  
  public function setVisible($faq_id)
  {
        Doctrine_Query::create()
                ->update('faq')
                ->set('status', '?', '1')
                ->where('id_faq = ' . $faq_id)
                ->execute();
  }  
  
  public function setHidden($faq_id)
  {
        Doctrine_Query::create()
                ->update('faq')
                ->set('status', '?', '0')
                ->where('id_faq = ' . $faq_id)
                ->execute();
  }
}