<?php

/**
 * Invite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    lufy
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Invite extends BaseInvite {

    public function setFalseInvite($idInvite) {
        $q = Doctrine_Query::create()
                        ->update('Invite i')
                        ->set('i.status', '?', '1')
                        ->set('i.updated_at', '?', date("Y-m-d h:i:s"))
                        ->where('i.id_invite = ?', $idInvite)
                        ->execute();
        return $q;
    }

    public function setAcceptInvite($idInvite) {
        $q = Doctrine_Query::create()
                        ->update('Invite i')
                        ->set('i.response', '?', 'accept')
                        ->set('i.updated_at', '?', date("Y-m-d h:i:s"))
                        ->where('i.id_invite = ?', $idInvite)
                        ->execute();
        return $q;
    }

    public function setRefuseInvite($idInvite) {
        $q = Doctrine_Query::create()
                        ->update('Invite i')
                        ->set('i.response', '?', 'refuse')
                        ->set('i.updated_at', '?', date("Y-m-d h:i:s"))
                        ->where('i.id_invite = ?', $idInvite)
                        ->execute();
        return $q;
    }

    public function getUser($id) {
        $q = Doctrine_Query::create()
                        ->from('sfGuardUser')
                        ->where('id = ?', $id)
                        ->execute();
        return $q[0];
    }

}