<?php

/**
 * PartnerType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    lufy
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PartnerType extends BasePartnerType
{
  public function __toString()
  {
    return $this->getName();
  }
  
  public function updatePosition(array $post)
  {
    $size = count($post);
    for($i=1; $i<=$size; $i++):
      $q = Doctrine_Query::create()
        ->update('partnerType')
        ->where('id_partner_type = ?', $post[$i][id])
        ->set('position ',$post[$i][position])
        ->execute();
    endfor;
  }
  
  public function setVisible($partner_type_id)
  {
        Doctrine_Query::create()
                ->update('partnerType')
                ->set('status', '?', '1')
                ->where('id_partner_type = ' . $partner_type_id)
                ->execute();
  }  
  
  public function setHidden($partner_type_id)
  {
        Doctrine_Query::create()
                ->update('partnerType')
                ->set('status', '?', '0')
                ->where('id_partner_type = ' . $partner_type_id)
                ->execute();
  }
}