<?php

/**
 * PayementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PayementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PayementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Payement');
    }
}