<?php

/**
 * PokerTournamentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PokerTournamentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PokerTournamentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PokerTournament');
    }
}