<?php

/**
 * PokerTournamentPlayerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PokerTournamentPlayerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PokerTournamentPlayerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PokerTournamentPlayer');
    }
}