<?php

/**
 * SfGuardUserAddressTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SfGuardUserAddressTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SfGuardUserAddressTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SfGuardUserAddress');
    }
}