<?php

/**
 * SfGuardUserProfile
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    lufy
 * @subpackage model
 * @author     Guillaume Marsay
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SfGuardUserProfile extends BaseSfGuardUserProfile
{
  public function save(Doctrine_Connection $conn = null)
  {
    if ($this->isNew() || !$this->getEan13())
    {
      $varConfig = Doctrine::getTable('VarConfig')->findOneByName('ean_next_player');
      $current_ean = new Ean13($varConfig->getValue());

      $this->setEan13($current_ean->get());

      $varConfig->setValue($current_ean->next()->get());
      $varConfig->save();
    }
    return parent::save($conn = null);
  }
}
