<?php

/**
 * SfGuardUserTshirtTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SfGuardUserTshirtTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SfGuardUserTshirtTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SfGuardUserTshirt');
    }
}