<?php

/**
 * SfGuardUserWeezeventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SfGuardUserWeezeventTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SfGuardUserWeezeventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SfGuardUserWeezevent');
    }
}