<?php

/**
 * SfGuardUserLicenceMasters
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    lufy
 * @subpackage model
 * @author     Guillaume Marsay
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SfGuardUserLicenceMasters extends BaseSfGuardUserLicenceMasters
{
}
