<?php

/**
 * SfGuardUserLicenceMastersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SfGuardUserLicenceMastersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SfGuardUserLicenceMastersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SfGuardUserLicenceMasters');
    }
}