<?php

/**
 * TeamPlayer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    lufy
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TeamPlayer extends BaseTeamPlayer {

    public function __toString() {
        return $this->getTeamId();
    }

	public function countPlayer($teamid)
	{
		$q =Doctrine_Query::create()
			->from('teamPlayer t')
                        ->where('team_id = ' . $teamid)
                        ->andWhere('is_player = 1')
                        ->execute();
		return count($q);
	}
	
}