<?php

/**
 * TicketFlagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TicketFlagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TicketFlagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TicketFlag');
    }
}