<?php

/**
 * TournamentSlot
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    lufy
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TournamentSlot extends BaseTournamentSlot
{
    public function __toString() {
      return $this->getIdTournamentSlot();
    }

    public function TeamName($team_id){
        if ($team_id != 0):
        $t = Doctrine::getTable('team')->findOneByIdTeam($team_id);
        
        return $t->getName();
        elseif ($team_id == 0):
            return '-';
        endif;
    }
    public function TeamSlug($team_id){
        $t = Doctrine::getTable('team')->findOneByIdTeam($team_id);

        return $t->getSlug();
    }
}