<?php

/**
 * TournamentAdmin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    lufy
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TournamentAdmin extends BaseTournamentAdmin
{
   public function getUsername ($id){
        $p = Doctrine::getTable('sfGuardUser')->findOneById($id);
        return $p->getUsername();
    }
}