<?php

/**
 * Tournament
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    lufy
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Tournament extends BaseTournament
{
  public function __toString()
  {
    return $this->getName();
  }


  public function registrationIsActive()
  {
    if ($this->getEvent()->registrationIsActive())
    {
      return true;
    }
    
    return false;
  }
  
  
  public function setVisible($tournament_id)
  {
    Doctrine_Query::create()
      ->update('tournament')
      ->set('is_active', '?', '1')
      ->where('id_tournament = ?', $tournament_id)
      ->execute();
  }  
  
  
  public function setHidden($tournament_id)
  {
    Doctrine_Query::create()
      ->update('tournament')
      ->set('is_active', '?', '0')
      ->where('id_tournament = ?', $tournament_id)
      ->execute();
  }
}