.TH "apps/presse/modules/news/templates/_actualite.php" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/presse/modules/news/templates/_actualite.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBuse_helper\fP ('bb')?><?php use_helper('Date')?>< ul ><?php \fBforeach\fP($actualites as $actualite)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "use_helper('bb')?><?php use_helper('Date')?>< ul ><?php \fBforeach\fP($actualites as $actualite)"

.PP
Definition at line 1 of file _actualite\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
