.TH "apps/live/modules/main/templates/_changeCulture.php" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/live/modules/main/templates/_changeCulture.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "& \fBnbsp\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "& nbsp"

.PP
Definition at line 2 of file _changeCulture\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
