.TH "apps/live/modules/comment/templates/_comments.php" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/live/modules/comment/templates/_comments.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBelse\fP \fB$image\fP = $comment->getSfGuardUser()->\fBgetLogourl\fP()"
.br
.ti -1c
.RI "le<?php echo $comment-> \fBgetCreatedAt\fP ()?> par< a href = '<?php echo url_for('user/view?username=' \&. $comment->getSfGuardUser()->getUsername());?>'><?php echo $comment->getSfGuardUser()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBelse\fP $image = $comment->getSfGuardUser()->\fBgetLogourl\fP()"

.PP
Definition at line 12 of file _comments\&.php\&.
.SS "le<?php echo $comment-> getCreatedAt()?> par< a href = '<?php echo url_for('user/view?username=' \&. $comment->getSfGuardUser()->getUsername());?>'><?php echo $comment->getSfGuardUser()"

.PP
Definition at line 16 of file _comments\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
