.TH "apps/frontend/templates/_flash.php" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/frontend/templates/_flash.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$type\fP = ''"
.br
.ti -1c
.RI "\fBif\fP($sf_user->isAuthenticated())($sf_user->
.br
hasFlash('error')) elseif($sf_user->
.br
hasFlash('warning')) elseif($sf_user->
.br
hasFlash('success')) \fBendif\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$type = ''"

.PP
Definition at line 2 of file _flash\&.php\&.
.SS "endif"

.PP
Definition at line 9 of file _flash\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
