.TH "apps/live/modules/user/templates/_form.php" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/live/modules/user/templates/_form.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBuse_stylesheets_for_form\fP ($form)?><?php use_javascripts_for_form($form)?>< span \fBstyle\fP = 'font-size: 10px; color: red;'><?php echo __('Les champs marques * sont obligatoires pour valider votre inscription a un tournoi\&.')"
.br
.ti -1c
.RI "\fBcolor\fP \fB__pad0__\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBcolor\fP __pad0__"

.PP
Definition at line 23 of file _form\&.php\&.
.SS "use_stylesheets_for_form($form)?><?php use_javascripts_for_form($form)?>< span \fBstyle\fP = 'font-size: 10px; color: red;'><?php echo __('Les champs marques * sont obligatoires pour valider votre inscription a un tournoi\&.')"

.PP
Definition at line 1 of file _form\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
