.TH "apps/live/modules/tournament/templates/_formTeam.php" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/live/modules/tournament/templates/_formTeam.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBuse_stylesheets_for_form\fP($form)?>
.br
<?php use_javascripts_for_form($form)?>
.br
< form action \fBif\fP (!$form->getObject()->isNew()) = 'post' <?php $form->isMultipart() and print 'enctype='multipart/form-data' '"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBuse_stylesheets_for_form\fP ($form) ?> <?php use_javascripts_for_form($form) ?> <form action if(!$form->getObject()->isNew()) = 'post' <?php $form->isMultipart() and print 'enctype='multipart/form-data' '"

.PP
Definition at line 5 of file _formTeam\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
