.TH "apps/live/modules/team/templates/_formFull.php" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/live/modules/team/templates/_formFull.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBuse_stylesheets_for_form\fP ($form)?><?php use_javascripts_for_form($form)?>< form action = 'post' <?php $form->isMultipart() and print 'enctype='multipart/form-data' '"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "use_stylesheets_for_form($form)?><?php use_javascripts_for_form($form)?>< form action = 'post' <?php $form->isMultipart() and print 'enctype='multipart/form-data' '"

.PP
Definition at line 1 of file _formFull\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
