.TH "apps/frontend/modules/invite/templates/_history.php" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/frontend/modules/invite/templates/_history.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBforeach\fP \fB($invites as $invite)\fP (!is_null($invite->getIsAccepted()))"
.br
.ti -1c
.RI "\fBelse\fP \fB__pad0__\fP"
.br
.ti -1c
.RI "\fBendif\fP"
.br
.ti -1c
.RI "\fBendforeach\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBforeach\fP ($invites as $invite)(!is_null($invite->getIsAccepted()))"

.PP
Definition at line 5 of file _history\&.php\&.
.SS "\fBelse\fP __pad0__"

.PP
Definition at line 14 of file _history\&.php\&.
.SS "endforeach"

.PP
Definition at line 19 of file _history\&.php\&.
.SS "endif"

.PP
Definition at line 15 of file _history\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
