.TH "apps/backend/templates/ Directory Reference" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/backend/templates/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBlayout\&.php\fP"
.br
.ti -1c
.RI "file \fBlogin\&.php\fP"
.br
.ti -1c
.RI "file \fBnologin\&.php\fP"
.br
.ti -1c
.RI "file \fBpopup\&.php\fP"
.br
.in -1c
