.TH "apps/live/config/ Directory Reference" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/live/config/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBgamersassemblyConfiguration\&.class\&.php\fP"
.br
.ti -1c
.RI "file \fBliveConfiguration\&.class\&.php\fP"
.br
.in -1c
