.TH "apps/frontend/modules/user/templates/ Directory Reference" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/frontend/modules/user/templates/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB_form\&.php\fP"
.br
.ti -1c
.RI "file \fB_formAddress\&.php\fP"
.br
.ti -1c
.RI "file \fB_formLicenceMasters\&.php\fP"
.br
.ti -1c
.RI "file \fBaddMastersSuccess\&.php\fP"
.br
.ti -1c
.RI "file \fBaddressSuccess\&.php\fP"
.br
.ti -1c
.RI "file \fBbulletinSuccess\&.php\fP"
.br
.ti -1c
.RI "file \fBeditAddressSuccess\&.php\fP"
.br
.ti -1c
.RI "file \fBeditProfileSuccess\&.php\fP"
.br
.ti -1c
.RI "file \fBlicenceMastersSuccess\&.php\fP"
.br
.ti -1c
.RI "file \fBnewAddressSuccess\&.php\fP"
.br
.ti -1c
.RI "file \fBpasswordSuccess\&.php\fP"
.br
.ti -1c
.RI "file \fBprofileSuccess\&.php\fP"
.br
.ti -1c
.RI "file \fBregisterSuccess\&.php\fP"
.br
.ti -1c
.RI "file \fBtshirtSuccess\&.php\fP"
.br
.ti -1c
.RI "file \fBviewSuccess\&.php\fP"
.br
.in -1c
