.TH "apps/frontend/modules/sfGuardAuth/templates/ Directory Reference" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/frontend/modules/sfGuardAuth/templates/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB_signin_form\&.php\fP"
.br
.ti -1c
.RI "file \fBsecureSuccess\&.php\fP"
.br
.ti -1c
.RI "file \fBsigninSuccess\&.php\fP"
.br
.in -1c
