.TH "apps/live/templates/ Directory Reference" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/live/templates/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB_footer\&.php\fP"
.br
.ti -1c
.RI "file \fB_navigation\&.php\fP"
.br
.ti -1c
.RI "file \fB_sidebar\&.php\fP"
.br
.ti -1c
.RI "file \fB_userbar\&.php\fP"
.br
.ti -1c
.RI "file \fBga2012\&.php\fP"
.br
.ti -1c
.RI "file \fBlayout\&.php\fP"
.br
.ti -1c
.RI "file \fBprint\&.php\fP"
.br
.in -1c
