.TH "apps/frontend/modules/invite/templates/ Directory Reference" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/frontend/modules/invite/templates/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB_history\&.php\fP"
.br
.ti -1c
.RI "file \fB_invitation\&.php\fP"
.br
.ti -1c
.RI "file \fB_nbinvite\&.php\fP"
.br
.ti -1c
.RI "file \fBaddFriendSuccess\&.php\fP"
.br
.ti -1c
.RI "file \fBaddPlayerSuccess\&.php\fP"
.br
.ti -1c
.RI "file \fBindexSuccess\&.php\fP"
.br
.in -1c
