.TH "apps/backend/modules/payement/templates/ Directory Reference" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/backend/modules/payement/templates/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB_form\&.php\fP"
.br
.ti -1c
.RI "file \fBdeleteSuccess\&.php\fP"
.br
.ti -1c
.RI "file \fBeditSuccess\&.php\fP"
.br
.ti -1c
.RI "file \fBindexSuccess\&.php\fP"
.br
.ti -1c
.RI "file \fBnewSuccess\&.php\fP"
.br
.ti -1c
.RI "file \fBvalidateIpnSuccess\&.php\fP"
.br
.in -1c
