.TH "apps/frontend/modules/tournament/templates/ Directory Reference" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/frontend/modules/tournament/templates/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB_formTeam\&.php\fP"
.br
.ti -1c
.RI "file \fB_nexttournament\&.php\fP"
.br
.ti -1c
.RI "file \fBaddTeamSuccess\&.php\fP"
.br
.ti -1c
.RI "file \fBindexSuccess\&.php\fP"
.br
.ti -1c
.RI "file \fBlistSuccess\&.php\fP"
.br
.ti -1c
.RI "file \fBreglementSuccess\&.php\fP"
.br
.ti -1c
.RI "file \fBviewSuccess\&.php\fP"
.br
.in -1c
