.TH "apps/frontend/modules/contact/templates/ Directory Reference" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/frontend/modules/contact/templates/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBaidesOrgasSuccess\&.php\fP"
.br
.ti -1c
.RI "file \fBindexSuccess\&.php\fP"
.br
.ti -1c
.RI "file \fBpartnerSuccess\&.php\fP"
.br
.ti -1c
.RI "file \fBpresseAccredSuccess\&.php\fP"
.br
.ti -1c
.RI "file \fBsendcontactpartnerSuccess\&.php\fP"
.br
.ti -1c
.RI "file \fBsendcontactSuccess\&.php\fP"
.br
.in -1c
