.TH "apps/live/modules/partner/templates/ Directory Reference" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/live/modules/partner/templates/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB_media\&.php\fP"
.br
.ti -1c
.RI "file \fB_officiel\&.php\fP"
.br
.ti -1c
.RI "file \fB_organisation\&.php\fP"
.br
.ti -1c
.RI "file \fB_principal\&.php\fP"
.br
.ti -1c
.RI "file \fB_rolling\&.php\fP"
.br
.ti -1c
.RI "file \fBindexSuccess\&.php\fP"
.br
.in -1c
