.TH "apps/frontend/modules/friend/ Directory Reference" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/frontend/modules/friend/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBactions\fP"
.br
.ti -1c
.RI "directory \fBtemplates\fP"
.br
.in -1c
