.TH "apps/presse/modules/ Directory Reference" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/presse/modules/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBevent\fP"
.br
.ti -1c
.RI "directory \fBfile\fP"
.br
.ti -1c
.RI "directory \fBgallery\fP"
.br
.ti -1c
.RI "directory \fBmain\fP"
.br
.ti -1c
.RI "directory \fBnews\fP"
.br
.ti -1c
.RI "directory \fBpage\fP"
.br
.ti -1c
.RI "directory \fBreader\fP"
.br
.in -1c
