.TH "apps/frontend/modules/invite/templates/_invitation.php" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/frontend/modules/invite/templates/_invitation.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBforeach\fP \fB($invites as $invite)\fP (is_null($invite->getIsAccepted()))"
.br
.ti -1c
.RI "\fBendif\fP"
.br
.ti -1c
.RI "\fBendforeach\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBforeach\fP ($invites as $invite)(is_null($invite->getIsAccepted()))"

.PP
Definition at line 5 of file _invitation\&.php\&.
.SS "endforeach"

.PP
Definition at line 20 of file _invitation\&.php\&.
.SS "endif"

.PP
Definition at line 14 of file _invitation\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
