.TH "apps/live/modules/block/templates/_list.php" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/live/modules/block/templates/_list.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBforeach\fP($blocks as $block)($block->
.br
getlink())?>'> <?php echo 
.br
image_tag('/uploads/encarts/' 
.br
\&. $block->getImage() $block 
.br
\fBgetTitle\fP ()\&. ''' \fBendforeach\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBforeach\fP ($blocks as $block) ($block->getlink())?>'> <?php echo image_tag('/uploads/encarts/' \&. $block->getImage() $block \fBgetTitle\fP ()\&. ''' endforeach"

.PP
Definition at line 3 of file _list\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
