.TH "apps/live/modules/comment/templates/_nbCommentByNews.php" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/live/modules/comment/templates/_nbCommentByNews.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$n\fP = $nb_comments"
.br
.ti -1c
.RI "\fBif\fP($n==0) elseif($n==1) \fBelse\fP"
.br
.ti -1c
.RI "\fBendif\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$n = $nb_comments"

.PP
Definition at line 2 of file _nbCommentByNews\&.php\&.
.SS "\fBif\fP ($n==0) elseif ($n==1) else"

.PP
Definition at line 6 of file _nbCommentByNews\&.php\&.
.SS "endif"

.PP
Definition at line 10 of file _nbCommentByNews\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
