.TH "apps/live/modules/event/templates/_nextevent.php" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/live/modules/event/templates/_nextevent.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBforeach\fP($nextevents as $event)($event->
.br
getEndAt()<$maintenant) \fBelse\fP"
.br
.ti -1c
.RI "\fBendif\fP"
.br
.ti -1c
.RI "\fBendforeach\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBforeach\fP ($nextevents as $event) ($event->getEndAt()<$maintenant) else"

.PP
Definition at line 4 of file _nextevent\&.php\&.
.SS "endforeach"

.PP
Definition at line 21 of file _nextevent\&.php\&.
.SS "endif"

.PP
Definition at line 17 of file _nextevent\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
