.TH "apps/live/modules/partner/templates/_organisation.php" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/live/modules/partner/templates/_organisation.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$i\fP = 0"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$\fBi\fP = 0"

.PP
Definition at line 3 of file _organisation\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
