.TH "apps/live/modules/team/templates/_players.php" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/live/modules/team/templates/_players.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$i\fP = '0'"
.br
.ti -1c
.RI "\fBforeach\fP ($players as $player)"
.br
.ti -1c
.RI "\fBif\fP (count($players) > $\fBi\fP)"
.br
.ti -1c
.RI "\fBendforeach\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$\fBi\fP = '0'"

.PP
Definition at line 3 of file _players\&.php\&.
.SS "endforeach"

.PP
Definition at line 11 of file _players\&.php\&.
.SS "foreach($players as $player)"

.PP
Definition at line 4 of file _players\&.php\&.
.SS "if(count($players) > $\fBi\fP)"

.PP
Definition at line 7 of file _players\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
