.TH "apps/frontend/modules/team/templates/_playersAdmin.php" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/frontend/modules/team/templates/_playersAdmin.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "</ul ></div ></td >< td > \fBendforeach\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "</ul></div></td><td> endforeach"

.PP
Definition at line 18 of file _playersAdmin\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
