.TH "apps/live/modules/partner/templates/_rolling.php" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/live/modules/partner/templates/_rolling.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBrolling\fP (\fBmin\fP, max, \fBi\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$i\fP = 0"
.br
.ti -1c
.RI "\fB$j\fP = 0"
.br
.ti -1c
.RI "\fBforeach\fP($partners as $partner)($\fBi\fP==0) \fBheight\fP"
.br
.ti -1c
.RI "width \fB__pad0__\fP"
.br
.ti -1c
.RI "width \fB__pad1__\fP"
.br
.ti -1c
.RI "< listyle='float:left;width:110px;text-align:center;line-height:90px;height:90px;'> \fBendif\fP"
.br
.ti -1c
.RI "\fBendforeach\fP"
.br
.ti -1c
.RI "\fBmin\fP = 0"
.br
.ti -1c
.RI "\fBi\fP = 0"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "rolling (\fBmin\fP, max, \fBi\fP)"

.PP
Definition at line 31 of file _rolling\&.php\&.
.SH "Variable Documentation"
.PP 
.SS "$\fBi\fP = 0"

.PP
Definition at line 2 of file _rolling\&.php\&.
.SS "$j = 0"

.PP
Definition at line 3 of file _rolling\&.php\&.
.SS "width __pad0__"

.PP
Definition at line 6 of file _rolling\&.php\&.
.SS "width __pad1__"

.PP
Definition at line 11 of file _rolling\&.php\&.
.SS "endforeach"

.PP
Definition at line 21 of file _rolling\&.php\&.
.SS "<listyle='float:left;width:110px;text-align:center;line-height:90px;height:90px;'> endif"

.PP
Definition at line 17 of file _rolling\&.php\&.
.SS "<listyle='width:220px;text-align:center;line-height:90px;height:90px;'> elseif ($i!=0 &&$\fBi\fP%2!=0) height"

.PP
Definition at line 4 of file _rolling\&.php\&.
.SS "i = 0"

.PP
Definition at line 29 of file _rolling\&.php\&.
.SS "min = 0"

.PP
Definition at line 28 of file _rolling\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
