.TH "apps/live/modules/tournament_slot/templates/_teamAndPlayers.php" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/live/modules/tournament_slot/templates/_teamAndPlayers.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBforeach\fP($slots as $slot)($\fBi\fP==$attente) \fBendif\fP"
.br
.ti -1c
.RI "\fBendforeach\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "endforeach"

.PP
Definition at line 24 of file _teamAndPlayers\&.php\&.
.SS "\fBforeach\fP ($slots as $slot) ($\fBi\fP==$attente) endif"

.PP
Definition at line 8 of file _teamAndPlayers\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
