.TH "apps/live/modules/tournament_slot/templates/_teamWithoutPlayers.php" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/live/modules/tournament_slot/templates/_teamWithoutPlayers.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBendif\fP"
.br
.ti -1c
.RI "\fBendforeach\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "endforeach"

.PP
Definition at line 37 of file _teamWithoutPlayers\&.php\&.
.SS "endif"

.PP
Definition at line 35 of file _teamWithoutPlayers\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
