.TH "apps/live/modules/main/templates/_twitter.php" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/live/modules/main/templates/_twitter.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBparse\fP ($text)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$user\fP = 'GamersAssembly'"
.br
.ti -1c
.RI "\fB$count\fP = 7"
.br
.ti -1c
.RI "\fB$date_format\fP = 'd M Y, H:i:s'"
.br
.ti -1c
.RI "\fB$url\fP = 'http://twitter\&.com/statuses/user_timeline/'\&.$user\&.'\&.xml?count='\&.$count"
.br
.ti -1c
.RI "\fB$oXML\fP = simplexml_load_file( $url )"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "parse ($text)"

.PP
Definition at line 3 of file _twitter\&.php\&.
.SH "Variable Documentation"
.PP 
.SS "$count = 7"

.PP
Definition at line 12 of file _twitter\&.php\&.
.SS "$date_format = 'd M Y, H:i:s'"

.PP
Definition at line 13 of file _twitter\&.php\&.
.SS "$oXML = simplexml_load_file( $url )"

.PP
Definition at line 15 of file _twitter\&.php\&.
.SS "$url = 'http://twitter\&.com/statuses/user_timeline/'\&.$user\&.'\&.xml?count='\&.$count"

.PP
Definition at line 14 of file _twitter\&.php\&.
.SS "$user = 'GamersAssembly'"

.PP
Definition at line 11 of file _twitter\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
