.TH "apps/live/templates/_userbar.php" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/live/templates/_userbar.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBif\fP \fB($sf_user->isAuthenticated())\fP (image_tag('13/house\&.png')\&.' '\&.$sf_user->getUsername(), 'user/index')?><?php \fBinclude_component\fP('invite'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBif\fP ($sf_user->isAuthenticated())(image_tag('13/house\&.png')\&.' '\&.$sf_user->getUsername(), 'user/index')?><?php \fBinclude_component\fP('invite'"

.PP
Definition at line 2 of file _userbar\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
