.TH "apps/frontend/templates/_user.php" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/frontend/templates/_user.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBendforeach\fP"
.br
.ti -1c
.RI "\fBelse\fP \fB__pad1__\fP"
.br
.ti -1c
.RI "\fBendif\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBelse\fP __pad1__"

.PP
Definition at line 16 of file _user\&.php\&.
.SS "endforeach"

.PP
Definition at line 14 of file _user\&.php\&.
.SS "endif"

.PP
Definition at line 17 of file _user\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
