.TH "apps/frontend/modules/poker_tournament/templates/addPlayerSuccess.php" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/frontend/modules/poker_tournament/templates/addPlayerSuccess.php \- 
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
