.TH "apps/frontend/modules/contact/templates/aidesOrgasSuccess.php" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/frontend/modules/contact/templates/aidesOrgasSuccess.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "v & \fBegrave\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "v& egrave"

.PP
Definition at line 74 of file aidesOrgasSuccess\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
