.TH "apps/backend/modules/page/templates/archivedSuccess.php" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/backend/modules/page/templates/archivedSuccess.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBforeach\fP \fB($pages as $page)\fP ()?></td >< td \fBstyle\fP = 'font-size: 10px;'><?php echo $page->getSlug()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBforeach\fP ($pages as $page)()?></td >< td \fBstyle\fP = 'font-size: 10px;'><?php echo $page->getSlug()"

.PP
Definition at line 14 of file archivedSuccess\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
