.TH "apps/live/modules/user/templates/bulletinSuccess.php" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/live/modules/user/templates/bulletinSuccess.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "imprimer et & \fBagrave\fP"
.br
.ti -1c
.RI "pr & \fBeacute\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "senter& agrave"

.PP
Definition at line 42 of file bulletinSuccess\&.php\&.
.SS "l identit& eacute"

.PP
Definition at line 42 of file bulletinSuccess\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
