.TH "commentComponents" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
commentComponents \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBexecuteNbCommentByNews\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteNbCommentByNewsLight\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteComments\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteNbCommentByNews\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteComments\fP (sfWebRequest $request)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBprocessFormComment\fP (sfWebRequest $request, sfForm $form)"
.br
.ti -1c
.RI "\fBprocessFormComment\fP (sfWebRequest $request, sfForm $form)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file components\&.class\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "executeComments (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 22 of file components\&.class\&.php\&.
.SS "executeComments (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 33 of file components\&.class\&.php\&.
.SS "executeNbCommentByNews (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 11 of file components\&.class\&.php\&.
.SS "executeNbCommentByNews (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 11 of file components\&.class\&.php\&.
.SS "executeNbCommentByNewsLight (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 22 of file components\&.class\&.php\&.
.SS "processFormComment (sfWebRequest$request, sfForm$form)\fC [protected]\fP"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 45 of file components\&.class\&.php\&.
.SS "processFormComment (sfWebRequest$request, sfForm$form)\fC [protected]\fP"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 56 of file components\&.class\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
