.TH "contactActions" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
contactActions \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBexecutePresseAccred\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecutePartner\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteSendcontactpartner\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteAidesOrgas\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteSendcontact\fP (sfWebRequest $request)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file actions\&.class\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "executeAidesOrgas (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 92 of file actions\&.class\&.php\&.
.SS "executePartner (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 30 of file actions\&.class\&.php\&.
.SS "executePresseAccred (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 19 of file actions\&.class\&.php\&.
.SS "executeSendcontact (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 102 of file actions\&.class\&.php\&.
.SS "executeSendcontactpartner (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 41 of file actions\&.class\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
