.TH "file_categoryActions" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
file_categoryActions \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBexecuteIndex\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteSwitchStatus\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteNew\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteCreate\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteEdit\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteUpdate\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteDelete\fP (sfWebRequest $request)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBprocessForm\fP (sfWebRequest $request, sfForm $form)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file actions\&.class\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "executeCreate (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 61 of file actions\&.class\&.php\&.
.SS "executeDelete (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 104 of file actions\&.class\&.php\&.
.SS "executeEdit (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 77 of file actions\&.class\&.php\&.
.SS "executeIndex (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 19 of file actions\&.class\&.php\&.
.SS "executeNew (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 51 of file actions\&.class\&.php\&.
.SS "executeSwitchStatus (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 31 of file actions\&.class\&.php\&.
.SS "executeUpdate (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 88 of file actions\&.class\&.php\&.
.SS "processForm (sfWebRequest$request, sfForm$form)\fC [protected]\fP"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 119 of file actions\&.class\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
