.TH "apps/frontend/config/frontendConfiguration.class.php" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/frontend/config/frontendConfiguration.class.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBfrontendConfiguration\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
