.TH "apps/live/templates/ga2012.php" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/live/templates/ga2012.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBgoogle_ad_slot\fP = '1479137562'"
.br
.ti -1c
.RI "\fBgoogle_ad_width\fP = 728"
.br
.ti -1c
.RI "\fBgoogle_ad_height\fP = 90"
.br
.ti -1c
.RI "\fBendif\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "endif"

.PP
Definition at line 77 of file ga2012\&.php\&.
.SS "google_ad_height = 90"

.PP
Definition at line 40 of file ga2012\&.php\&.
.SS "google_ad_slot = '1479137562'"

.PP
Definition at line 38 of file ga2012\&.php\&.
.SS "google_ad_width = 728"

.PP
Definition at line 39 of file ga2012\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
