.TH "galleryComponents" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
galleryComponents \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBexecuteList\fP (sfWebRequest $request)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file components\&.class\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "executeList (sfWebRequest$request)"

.PP
Definition at line 5 of file components\&.class\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
