.TH "inviteComponents" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inviteComponents \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBexecuteNbinvite\fP (sfWebRequest $request)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file components\&.class\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "executeNbinvite (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 10 of file components\&.class\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
