.TH "apps/presse/templates/layout.php" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/presse/templates/layout.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "include_http_metas()?><?php 
.br
include_metas()?><?php 
.br
include_title()?>< link rel \fBinclude_javascripts\fP ()?></head >< body >< div \fBid\fP"
.br
.ti -1c
.RI "& \fBnbsp\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "include_http_metas () ?> <?php include_metas() ?> <?php include_title() ?> <link rel include_javascripts()?></head >< body >< div \fBid\fP"
\fBInitial value:\fP
.PP
.nf
'width: 1100px; margin: auto auto;'>
        <div>
            <?php echo link_to('Presse & Partenaires', '@homepage', array('style' => 'color: #0195bb;'))
.fi
.PP
Definition at line 9 of file layout\&.php\&.
.SS "& nbsp"

.PP
Definition at line 36 of file layout\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
