.TH "apps/frontend/modules/user/templates/licenceMastersSuccess.php" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/frontend/modules/user/templates/licenceMastersSuccess.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBelse\fP \fB__pad0__\fP"
.br
.ti -1c
.RI "\fBendif\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBelse\fP __pad0__"

.PP
Definition at line 5 of file licenceMastersSuccess\&.php\&.
.SS "endif"

.PP
Definition at line 40 of file licenceMastersSuccess\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
