.TH "apps/live/modules/user/templates/licenceSuccess.php" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/live/modules/user/templates/licenceSuccess.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBelse\fP \fB__pad1__\fP"
.br
.ti -1c
.RI "\fBendif\fP"
.br
.ti -1c
.RI "\fBelse\fP \fB__pad2__\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBelse\fP __pad1__"

.PP
Definition at line 7 of file licenceSuccess\&.php\&.
.SS "\fBelse\fP __pad2__"

.PP
Definition at line 14 of file licenceSuccess\&.php\&.
.SS "endif"

.PP
Definition at line 8 of file licenceSuccess\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
