.TH "liveConfiguration" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
liveConfiguration \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBconfigure\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file liveConfiguration\&.class\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "configure ()"

.PP
Definition at line 5 of file liveConfiguration\&.class\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
