.TH "lufy" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lufy \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
block actions\&.
.PP
block 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
commande actions\&.
.PP
commande 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
comment actions\&.
.PP
comment 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
event actions\&.
.PP
event 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
faq actions\&.
.PP
faq 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
file actions\&.
.PP
file 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
file_category actions\&.
.PP
file_category 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
file_type actions\&.
.PP
file_type 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
friend actions\&.
.PP
friend 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
gallery actions\&.
.PP
gallery 
.PP
\fBAuthor:\fP
.RS 4
Guillaume Marsay guillaume@futurolan.net
.RE
.PP
game actions\&.
.PP
game 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
game_type actions\&.
.PP
game_type 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
invite actions\&.
.PP
invite 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
ipn actions\&.
.PP
ipn 
.PP
\fBAuthor:\fP
.RS 4
Guillaume Marsay guillaume@futurolan.net 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
mail actions\&.
.PP
mail 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
main actions\&.
.PP
main 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
news actions\&.
.PP
news 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
news_type actions\&.
.PP
news_type 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
newsletter actions\&.
.PP
newsletter 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
page actions\&.
.PP
page 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
pageType actions\&.
.PP
pageType 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
partner actions\&.
.PP
partner 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
partner_type actions\&.
.PP
partner_type 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
payement actions\&.
.PP
payement 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
plateform actions\&.
.PP
plateform 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
poker_tournament actions\&.
.PP
poker_tournament 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
poker_tournament_player actions\&.
.PP
poker_tournament_player 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
stats actions\&.
.PP
stats 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
status_slot actions\&.
.PP
status_slot 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
team actions\&.
.PP
team 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
ticket actions\&.
.PP
ticket 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
tournament actions\&.
.PP
tournament 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
tournament_admin actions\&.
.PP
tournament_admin 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
tournament_slot actions\&.
.PP
tournament_slot 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
upload actions\&.
.PP
upload 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
user actions\&.
.PP
user 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
var_config actions\&.
.PP
var_config 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
contact actions\&.
.PP
contact 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
feed actions\&.
.PP
feed 
.PP
\fBAuthor:\fP
.RS 4
Guillaume Marsay 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
gallery actions\&.
.PP
gallery 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
main components\&.
.PP
main 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
components\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
news actions\&.
.PP
news 
.PP
\fBAuthor:\fP
.RS 4
Guillaume Marsay guillaume@futurolan.Net 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
partner actions\&.
.PP
partner 
.PP
\fBAuthor:\fP
.RS 4
Guillaume Marsay guillaume@futurolan.net
.RE
.PP
poker_player actions\&.
.PP
poker_player 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
poker_player components\&.
.PP
poker_player 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
components\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
search actions\&.
.PP
search 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
team actions\&.
.PP
team 
.PP
\fBAuthor:\fP
.RS 4
Guillaume Marsay guillaume@futurolan.net 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
user actions\&.
.PP
user 
.PP
\fBAuthor:\fP
.RS 4
Guillaume Marsay guillaume@futurolan.net 
.PP
HumanG33k 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
event actions\&.
.PP
event 
.PP
\fBAuthor:\fP
.RS 4
Guillaume Marsay guillaume@futurolan.net 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP
.PP
reader actions\&.
.PP
reader 
.PP
\fBAuthor:\fP
.RS 4
Your name here 
.RE
.PP
\fBVersion:\fP
.RS 4
SVN: 
.RE
.PP
\fBId:\fP
.RS 4
actions\&.class\&.php 23810 2009-11-12 11:07:44Z Kris\&.Wallsmith 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
