.TH "mainActions" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mainActions \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBexecuteIndex\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteGamersassembly\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteLogin\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteParameters\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteClearCache\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteError404\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteError401\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteIndex\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteLanguage\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteChangeLanguage\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteError404\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteError401\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteIndex\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteLanguage\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteChangeLanguage\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteError404\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteError401\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteIndex\fP (sfWebRequest $request)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file actions\&.class\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "executeChangeLanguage (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 43 of file actions\&.class\&.php\&.
.SS "executeChangeLanguage (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 44 of file actions\&.class\&.php\&.
.SS "executeClearCache (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 85 of file actions\&.class\&.php\&.
.SS "executeError401 (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 67 of file actions\&.class\&.php\&.
.SS "executeError401 (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 69 of file actions\&.class\&.php\&.
.SS "executeError401 (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 111 of file actions\&.class\&.php\&.
.SS "executeError404 (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 56 of file actions\&.class\&.php\&.
.SS "executeError404 (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 58 of file actions\&.class\&.php\&.
.SS "executeError404 (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 100 of file actions\&.class\&.php\&.
.SS "executeGamersassembly (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 30 of file actions\&.class\&.php\&.
.SS "executeIndex (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 19 of file actions\&.class\&.php\&.
.SS "executeIndex (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 20 of file actions\&.class\&.php\&.
.SS "executeIndex (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 20 of file actions\&.class\&.php\&.
.SS "executeIndex (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 20 of file actions\&.class\&.php\&.
.SS "executeLanguage (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 31 of file actions\&.class\&.php\&.
.SS "executeLanguage (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 31 of file actions\&.class\&.php\&.
.SS "executeLogin (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 65 of file actions\&.class\&.php\&.
.SS "executeParameters (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 75 of file actions\&.class\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
