.TH "myUser" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
myUser \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetId\fP ()"
.br
.ti -1c
.RI "\fBgetUsername\fP ()"
.br
.ti -1c
.RI "\fBgetEmailAddress\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file myUser\&.class\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getEmailAddress ()"

.PP
Definition at line 15 of file myUser\&.class\&.php\&.
.SS "getId ()"

.PP
Definition at line 5 of file myUser\&.class\&.php\&.
.SS "getUsername ()"

.PP
Definition at line 10 of file myUser\&.class\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
