.TH "newsComponents" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
newsComponents \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBexecuteActualite\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteActualitelight\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteAffiche\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteActualite\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteActualitelight\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteAffiche\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteActualite\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteActualitelight\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteAffiche\fP (sfWebRequest $request)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file components\&.class\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "executeActualite (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 11 of file components\&.class\&.php\&.
.SS "executeActualite (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 11 of file components\&.class\&.php\&.
.SS "executeActualite (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 11 of file components\&.class\&.php\&.
.SS "executeActualitelight (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 40 of file components\&.class\&.php\&.
.SS "executeActualitelight (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 40 of file components\&.class\&.php\&.
.SS "executeActualitelight (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 52 of file components\&.class\&.php\&.
.SS "executeAffiche (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 68 of file components\&.class\&.php\&.
.SS "executeAffiche (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 69 of file components\&.class\&.php\&.
.SS "executeAffiche (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 93 of file components\&.class\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
