.TH "newsActions" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
newsActions \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBexecuteIndex\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecutePreview\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteSwitchStatus\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteComments\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteSet\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteNew\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteCreate\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteEdit\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteUpdate\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteDelete\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteIndex\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteView\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteIndex\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteView\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteIndex\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteView\fP (sfWebRequest $request)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBprocessForm\fP (sfWebRequest $request, sfForm $form)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file actions\&.class\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "executeComments (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 77 of file actions\&.class\&.php\&.
.SS "executeCreate (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 135 of file actions\&.class\&.php\&.
.SS "executeDelete (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 178 of file actions\&.class\&.php\&.
.SS "executeEdit (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 151 of file actions\&.class\&.php\&.
.SS "executeIndex (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 19 of file actions\&.class\&.php\&.
.SS "executeIndex (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 19 of file actions\&.class\&.php\&.
.SS "executeIndex (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 19 of file actions\&.class\&.php\&.
.SS "executeIndex (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 19 of file actions\&.class\&.php\&.
.SS "executeNew (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 118 of file actions\&.class\&.php\&.
.SS "executePreview (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 46 of file actions\&.class\&.php\&.
.SS "executeSet (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 90 of file actions\&.class\&.php\&.
.SS "executeSwitchStatus (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 57 of file actions\&.class\&.php\&.
.SS "executeUpdate (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 162 of file actions\&.class\&.php\&.
.SS "executeView (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 48 of file actions\&.class\&.php\&.
.SS "executeView (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 48 of file actions\&.class\&.php\&.
.SS "executeView (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 60 of file actions\&.class\&.php\&.
.SS "processForm (sfWebRequest$request, sfForm$form)\fC [protected]\fP"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 197 of file actions\&.class\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
