.TH "pageActions" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pageActions \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBexecuteIndex\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteArchived\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteArchive\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteUnarchive\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteNew\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteCreate\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteEdit\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteUpdate\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteDuplicate\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteDelete\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteView\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteConcoursOuikos\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteView\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteConcoursOuikos\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteView\fP (sfWebRequest $request)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBprocessForm\fP (sfWebRequest $request, sfForm $form)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file actions\&.class\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "executeArchive (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 64 of file actions\&.class\&.php\&.
.SS "executeArchived (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 41 of file actions\&.class\&.php\&.
.SS "executeConcoursOuikos (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 45 of file actions\&.class\&.php\&.
.SS "executeConcoursOuikos (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 48 of file actions\&.class\&.php\&.
.SS "executeCreate (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 102 of file actions\&.class\&.php\&.
.SS "executeDelete (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 184 of file actions\&.class\&.php\&.
.SS "executeDuplicate (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 163 of file actions\&.class\&.php\&.
.SS "executeEdit (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 118 of file actions\&.class\&.php\&.
.SS "executeIndex (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 19 of file actions\&.class\&.php\&.
.SS "executeNew (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 92 of file actions\&.class\&.php\&.
.SS "executeUnarchive (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 78 of file actions\&.class\&.php\&.
.SS "executeUpdate (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 147 of file actions\&.class\&.php\&.
.SS "executeView (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 19 of file actions\&.class\&.php\&.
.SS "executeView (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 19 of file actions\&.class\&.php\&.
.SS "executeView (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 19 of file actions\&.class\&.php\&.
.SS "processForm (sfWebRequest$request, sfForm$form)\fC [protected]\fP"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 200 of file actions\&.class\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
