.TH "partnerComponents" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
partnerComponents \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBexecuteRolling\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteRolling\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecutePrincipal\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteOfficiel\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteOrganisation\fP (sfWebRequest $request)"
.br
.ti -1c
.RI "\fBexecuteMedia\fP (sfWebRequest $request)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file components\&.class\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "executeMedia (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 88 of file components\&.class\&.php\&.
.SS "executeOfficiel (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 43 of file components\&.class\&.php\&.
.SS "executeOrganisation (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 64 of file components\&.class\&.php\&.
.SS "executePrincipal (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 25 of file components\&.class\&.php\&.
.SS "executeRolling (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 11 of file components\&.class\&.php\&.
.SS "executeRolling (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 11 of file components\&.class\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
