.TH "apps/live/modules/tournament_slot/templates/paymentSuccess.php" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/live/modules/tournament_slot/templates/paymentSuccess.php \- 
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
