.TH "apps/backend/modules/news/templates/previewSuccess.php" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/backend/modules/news/templates/previewSuccess.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "font \fBsize\fP = $news->\fBgetTitle\fP()"
.br
.ti -1c
.RI "margin \fBbottom\fP"
.br
.ti -1c
.RI "\fBpadding\fP \fB__pad2__\fP"
.br
.ti -1c
.RI "background \fBcolor\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBpadding\fP __pad2__"

.PP
Definition at line 32 of file previewSuccess\&.php\&.
.SS "margin bottom"

.PP
Definition at line 31 of file previewSuccess\&.php\&.
.SS "background color"

.PP
Definition at line 33 of file previewSuccess\&.php\&.
.SS "font size = $news->\fBgetTitle\fP()"

.PP
Definition at line 3 of file previewSuccess\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
