.TH "searchActions" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
searchActions \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBexecuteUser\fP (sfWebRequest $request)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file actions\&.class\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "executeUser (sfWebRequest$request)"
\fBParameters:\fP
.RS 4
\fI@return\fP 
.RE
.PP

.PP
Definition at line 19 of file actions\&.class\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
