.TH "apps/backend/modules/tournament_slot/templates/tournamentSuccess.php" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/backend/modules/tournament_slot/templates/tournamentSuccess.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBelse\fP"
.br
.ti -1c
.RI "\fBendif\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "else"

.PP
Definition at line 17 of file tournamentSuccess\&.php\&.
.SS "endif"

.PP
Definition at line 21 of file tournamentSuccess\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
