.TH "apps/frontend/modules/search/templates/userSuccess.php" 3 "Thu Jun 6 2013" "Lufy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/frontend/modules/search/templates/userSuccess.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBendforeach\fP"
.br
.ti -1c
.RI "\fBendif\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "endforeach"

.PP
Definition at line 22 of file userSuccess\&.php\&.
.SS "endif"

.PP
Definition at line 24 of file userSuccess\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Lufy from the source code\&.
