# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Gamers Assembly 2013
    description:  Gamers Assembly 2013, Palais des Congres du Futuroscope
    keywords:     Gamers Assembly, Futurolan, LAN Party, Masters Jeu Video, Palais des Congres
    language:     fr
    #robots:      index, follow

  stylesheets:
    - ../bootstrap/css/bootstrap.min.css
    - ../bootstrap/css/bootstrap-responsive.min.css
    - ../font-awesome/css/font-awesome.min.css
    - frontend/styles.css
    - frontend/ga2014/styles.css

  javascripts:
    - jquery-1.7.1.min.js
    - ../bootstrap/js/bootstrap.min.js
    - jquery.bubble.js

  has_layout:     true
  layout:         layout
