<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    lufy
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{
  public function __toString()
  {
    return $this->getUsername();
  }

 
  public function hasTeam()
  {
    if ($this->getTeamPlayer()->count() > 0)
    {
      return true;
    }
    
    return false;
  }
  
  
  public function getDefaultAddress()
  {
    return SfGuardUserAddressTable::getDefaultAddressByUserId($this->getId());
  }

  
  public function getBillingAddress()
  {
    return SfGuardUserAddressTable::getDefaultAddressByUserId($this->getId());
  }

  
  public function getDeliveryAddress()
  {
    return SfGuardUserAddressTable::getDefaultAddressByUserId($this->getId());
  }
}
