<?php

class lufyGenerateFixturesTask extends sfBaseTask
{
  protected function configure()
  {
    $this->namespace        = 'lufy';
    $this->name             = 'generate-fixtures';
    $this->briefDescription = 'Genere les fixtures de test';
    $this->detailedDescription = <<<EOF
The [lufy:generate-fixtures|INFO] task does things.
Call it with:

  [php symfony lufy:generate-fixtures|INFO]
EOF;
  }

  protected function execute($arguments = array(), $options = array())
  {
    $yaml = array();

    $this->logSection('info', 'Generation des fixtures pour sfGuardPermission');

    /* Configuration */

    $this->fixtures_path = dirname(__FILE__).'/../../data/fixtures/';

    $permission_levels = array(
      'viewer',
      'writer'
    );

    $modules = sfFinder::type('dir')
      ->relative()
      ->maxdepth(0)
      ->in(dirname(__FILE__).'/../../apps/backend/modules/');


    /* Fixtures sfGuardGroup */

    $yaml[] = 'sfGuardGroup:';
    $yaml[] = '  Group_ChuckNorris:';
    $yaml[] = '    name:        "Administrateur"';
    $yaml[] = '    description: "Administateur"';
    $permissions = '    Permissions: [';
    foreach ($modules as $module)
    {
      foreach ($permission_levels as $level)
      {
        $permissions.= 'Permission_'.$module.'_'.$level.', ';
      }
    }
    $permissions = substr($permissions, 0, -2);
    $permissions.= ']';
    $yaml[] = $permissions;

    $yaml[] = '  Group_Editor:';
    $yaml[] = '    name:        "Editeur"';
    $yaml[] = '    description: "Editeur"';
    $permissions = '    Permissions: [';
    foreach ($modules as $module)
    {
      $permissions.= 'Permission_'.$module.'_writer, ';
    }
    $permissions = substr($permissions, 0, -2);
    $permissions.= ']';
    $yaml[] = $permissions;

    $yaml[] = '  Group_Viewer:';
    $yaml[] = '    name:        "Viewer"';
    $yaml[] = '    description: "Viewer"';
    $permissions = '    Permissions: [';
    foreach ($modules as $module)
    {
      $permissions.= 'Permission_'.$module.'_viewer, ';
    }
    $permissions = substr($permissions, 0, -2);
    $permissions.= ']';
    $yaml[] = $permissions;


    /* Fixtures sfGuardPermission */

    $yaml[] = 'sfGuardPermission:';

    foreach ($modules as $module)
    {
      foreach ($permission_levels as $level)
      {
        $yaml[] = '  Permission_'.$module.'_'.$level.':';
        $yaml[] = '    name:        '.$module.'_'.$level;
        $yaml[] = '    description: '.str_replace('_', ' ', ucfirst($module)).' '.$level;
      }
    }

    $this->render($yaml);
  }

  protected function render($yaml)
  {
    $render = '# Generated by php symfony lufy:generate-fixtures'."\n";
    $render.= '# '.date('d F Y')."\n";
    foreach ($yaml as $line)
    {
      if (substr($line, 0, 1) != ' ')
      {
        $render.= "\n";
      }

      $render.= $line."\n";
    }

    file_put_contents($this->fixtures_path.'sfGuard.yml', $render);
  }
}
