TicketFlag:
  connection: doctrine
  tableName: ticket_flag
  columns:
    id:
      type: integer(8)
      primary: true
      autoincrement: true
    name:
      type: string(20)
      notnull: true
    color:
      type: string(6)
      notnull: true
      default: "000000"
    is_closed:
      type: boolean
      default: false
  relations:
    Tickets:
      class: Ticket
      foreignAlias: Tickets
      refClass: TicketFlagTicket

Ticket:
  connection: doctrine
  tableName: ticket
  actAs:
    Timestampable: ~
  columns:
    id:
      type: integer(8)
      primary: true
      autoincrement: true
    user_id:
      type: integer(8)
      notnull: true
    assigned_at:
      type: integer(8)
      notnull: false
    title:
      type: string(50)
      notnull: true
    content:
      type: string()
      notnull: false
    parent_id:
      type: integer(8)
      notnull: false
  relations:
    SfGuardUser:
      class: sfGuardUser
      local: user_id
      foreign: id
      type: one
    Owner:
      class: sfGuardUser
      local: assigned_at
      foreign: id
      type: one
    Parent:
      class: Ticket
      local: parent_id
      foreign: id
      type: one
    Flags:
      class: TicketFlag
      foreignAlias: Flags
      refClass: TicketFlagTicket

TicketFlagTicket:
  columns:
    ticket_flag_id:
      type: integer(8)
      primary: true
    ticket_id:
      type: integer(8)
      primary: true
  relations:
    Flag: ~
    Ticket: ~

Block:
  connection: doctrine
  tableName: block
  columns:
    id_block:
      type: integer(4)
      primary: true
      autoincrement: true
    title:
      type: string(50)
      notnull: true
    content:
      type: string()
    image:
      type: string(255)
    link:
      type: string(255)
    position:
      type: integer(4)
    is_active:
      type: boolean
      default: false


Event:
  connection: doctrine
  tableName: event
  actAs:
    Sluggable:
      fields: [name]
  columns:
    id_event:
      type: integer(4)
      primary: true
      autoincrement: true
    weezevent_id:
      type: string(50)
      notnull: false
    name:
      type: string(45)
      notnull: true
    description:
      type: text
      notnull: false
    image:
      type: string(255)
    start_at:
      type: timestamp(25)
      notnull: false
    end_at:
      type: timestamp(25)
      notnull: false
    start_registration_at:
      type: timestamp(25)
      notnull: false
    end_registration_at:
      type: timestamp(25)
      notnull: false
    address:
      type: text
      notnull: false
    map_url:
      type: text
      notnull: false
  relations:
    Tournament:
      local: id_event
      foreign: event_id
      type: many

Friend:
  connection: doctrine
  tableName: friend
  columns:
    id_friend:
      type: integer(8)
      primary: true
      autoincrement: true
    user_id:
      type: integer(8)
      notnull: true
    friend_id:
      type: integer(8)
      notnull: true
  relations:
    SfGuardUser:
      class: sfGuardUser
      local: friend_id
      foreign: id
      type: one

Game:
  connection: doctrine
  tableName: game
  columns:
    id_game:
      type: integer(4)
      primary: true
      autoincrement: true
    game_type_id:
      type: integer(4)
      notnull: true
    plateform_id:
      type: integer(4)
      notnull: false
    label:
      type: string(45)
      notnull: true
    editor:
      type: string(100)
    year:
        type: string(50)
    description:
      type: string(255)
      notnull: true
    logourl:
      type: string(255)
      notnull: false
  relations:
    GameType:
      local: game_type_id
      foreign: id_game_type
      type: one
    Plateform:
      local: plateform_id
      foreign: id_plateform
      type: one
    Tournament:
      local: id_game
      foreign: game_id
      type: many

GameType:
  connection: doctrine
  tableName: game_type
  columns:
    id_game_type:
      type: integer(4)
      primary: true
      autoincrement: true
    label:
      type: string(45)
      notnull: true
  relations:
    Game:
      local: id_game_type
      foreign: game_type_id
      type: many

Page:
  connection: doctrine
  tableName: page
  actAs:
    Timestampable: ~
    Sluggable:
      fields: [title]
  columns:
    id_page:
      type: integer(4)
      primary: true
      autoincrement: true
    title:
      type: string(250)
      notnull: true
    content:
      type: text
      notnull: false
    status:
      type: integer(4)
      notnull: false
      default: 0
    publish_on:
      type: timestamp(25)
      notnull: true
    page_type_id:
      type: integer(4)
      notnull: true
  relations:
    PageType:
      local: page_type_id
      foreign: id_page_type
      type: one

PageType:
  connection: doctrine
  tableName: page_type
  columns:
    id_page_type:
      type: integer(4)
      primary: true
      autoincrement: true
    label:
      type: string(100)
      notnull: true
    description:
      type: text
      notnull: false
  relations:
    Page:
      local: id_page_type
      foreign: page_type_id
      type: many

News:
  connection: doctrine
  tableName: news
  actAs:
    Timestampable: ~
    Sluggable:
      fields: [title]
  columns:
    id_news:
      type: integer(4)
      primary: true
      autoincrement: true
    user_id:
      type: integer(8)
      notnull: false
    title:
      type: string(250)
      notnull: true
    summary:
      type: text
      notnull: false
    content:
      type: text
      notnull: false
    status:
      type: string(45)
      notnull: true
    publish_on:
      type: timestamp(25)
      notnull: true
    image:
      type: string(250)
      notnull: false
    news_type_id:
      type: integer(4)
      notnull: true
  relations:
    NewsType:
      local: news_type_id
      foreign: id_news_type
      type: one
    SfGuardUser:
      class: sfGuardUser
      local: user_id
      foreign: id
      type: one

NewsType:
  connection: doctrine
  tableName: news_type
  columns:
    id_news_type:
      type: integer(4)
      primary: true
      autoincrement: true
    label:
      type: string(100)
      notnull: true
    description:
      type: text
      notnull: false
    logourl:
      type: string(250)
      notnull: false
    is_special:
      type: integer(4)
      notnull: true
  relations:
    News:
      local: id_news_type
      foreign: news_type_id
      type: many

Newsletter:
  connection: doctrine
  tableName: newsletter
  actAs:
    Timestampable: ~
  columns:
    id_newsletter:
      type: integer(4)
      primary: true
      autoincrement: true
    recipient:
      type: string(255)
      notnull: true
    subject:
      type: string(255)
      notnull: true
    content:
      type: text
      notnull: true

Mail:
  connection: doctrine
  tableName: mail
  actAs:
    Timestampable: ~
  columns:
    id_mail:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
    description:
      type: string(255)
      notnull: true
    email:
      type: string(255)
      notnull: true
    subject:
      type: string(255)
      notnull: true
    content:
      type: text
      notnull: true

Partner:
  connection: doctrine
  tableName: partner
  columns:
    id_partner:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(45)
      notnull: true
    description:
      type: text
      notnull: false
    logourl:
      type: string(250)
      notnull: false
    website:
      type: string(250)
      notnull: false
    status:
      type: string(45)
      notnull: true
    position:
      type: integer(4)
      notnull: false
    partner_type_id:
      type: integer(4)
      notnull: true
  relations:
    PartnerType:
      local: partner_type_id
      foreign: id_partner_type
      type: one

PartnerType:
  connection: doctrine
  tableName: partner_type
  columns:
    id_partner_type:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(100)
      notnull: true
    description:
      type: text
      notnull: false
    status:
      type: string(45)
      notnull: false
    position:
      type: integer(4)
      notnull: false
  relations:
    Partner:
      local: id_partner_type
      foreign: partner_type_id
      type: many

Plateform:
  connection: doctrine
  tableName: plateform
  columns:
    id_plateform:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: varchar(100)
    tag:
      type: varchar(10)
    constructor:
      type: varchar(100)
  relations:
    Game:
      local: id_plateform
      foreign: plateform_id
      type: one

Team:
  connection: doctrine
  tableName: team
  actAs:
    Timestampable: ~
    Sluggable:
      fields: [name]
  columns:
    id_team:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(45)
      notnull: true
    tag:
      type: string(10)
      notnull: false
    country:
      type: string(10)
      notnull: false
    description:
      type: text
      notnull: false
    website:
      type: string(250)
      notnull: false
    logourl:
      type: string(250)
      notnull: false
    is_locked:
      type: boolean
      default: false
  relations:
    Invite:
      local: id_team
      foreign: team_id
      type: many
    TeamPlayer:
      onDelete: CASCADE
      local: id_team
      foreign: team_id
      type: many
    TournamentSlot:
      local: id_team
      foreign: team_id
      type: one

TeamPlayer:
  connection: doctrine
  tableName: team_player
  columns:
    team_id:
      type: integer(4)
      notnull: true
      primary: true
    user_id:
      type: integer(8)
      notnull: true
      primary: true
    is_captain:
      type: boolean
      default: false
    is_player:
      type: boolean
      default: false
  relations:
    Team:
      local: team_id
      foreign: id_team
      type: one
    SfGuardUser:
      class: sfGuardUser
      local: user_id
      foreign: id
      type: one

Tournament:
  connection: doctrine
  tableName: tournament
  actAs:
    Sluggable:
      fields: [name]
  columns:
    id_tournament:
      type: integer(4)
      primary: true
      autoincrement: true
    game_id:
      type: integer(4)
      notnull: true
    event_id:
      type: integer(4)
      notnull: true
    weezevent_id:
      type: string(50)
      notnull: false
    name:
      type: string(45)
      notnull: true
    number_team:
      type: integer(4)
      default: '1'
      notnull: true
    player_per_team:
      type: integer(4)
      default: '1'
      notnull: true
    cost_per_player:
      type: 'decimal(10, 2)'
      default: '0.00'
      notnull: true
    reserved_slot:
      type: integer(4)
      default: '0'
      notnull: true
    start_at:
      type: timestamp(25)
      notnull: false
    end_at:
      type: timestamp(25)
      notnull: false
    logourl:
      type: string(250)
      notnull: true
    description:
      type: string(255)
      notnull: false
    position:
      type: integer(4)
    is_active:
      type: boolean
      default: false
  relations:
    Event:
      local: event_id
      foreign: id_event
      type: one
    Game:
      local: game_id
      foreign: id_game
      type: one
    TournamentAdmin:
      local: id_tournament
      foreign: tournament_id
      type: many
    TournamentTeam:
      local: id_tournament
      foreign: tournament_id
      type: many
    TournamentSlot:
      local: id_tournament
      foreign: tournament_id
      type: many

TournamentAdmin:
  connection: doctrine
  tableName: tournament_admin
  columns:
    id_tournament_admin:
      type: integer(4)
      primary: true
      autoincrement: true
    user_id:
      type: integer(8)
      notnull: true
    tournament_id:
      type: integer(4)
      default: '0'
      notnull: true
  relations:
    Tournament:
      local: tournament_id
      foreign: id_tournament
      type: one
    SfGuardUser:
      class: sfGuardUser
      local: user_id
      foreign: id
      type: one

TournamentSlot:
  connection: doctrine
  tableName: tournament_slot
  actAs:
    Timestampable: ~
  columns:
    id_tournament_slot:
      type: integer(4)
      primary: true
      autoincrement: true
    team_id:
      type: integer(4)
      notnull: true
    tournament_id:
      type: integer(4)
      notnull: true
    is_valid:
      type: boolean
      default: false
    is_locked:
      type: boolean
      default: false
  relations:
    Team:
      local: team_id
      foreign: id_team
      type: one
    Tournament:
      local: tournament_id
      foreign: id_tournament
      type: one


Invite:
  connection: doctrine
  tableName: invite
  actAs:
    Timestampable: ~
  columns:
    id_invite:
      type: integer(8)
      primary: true
      autoincrement: true
    team_id:
      type: integer(4)
    user_id:
      type: integer(8)
    is_accepted:
      type: boolean
      default: null
      notnull: false
  relations:
    Team:
      local: team_id
      foreign: id_team
      type: one
    SfGuardUser:
      class: sfGuardUser
      local: user_id
      foreign: id
      type: one

VarConfig:
  connection: doctrine
  tableName: var_config
  columns:
    id_var:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: varchar(100)
      notnull: true
    value:
      type: text()
      notnull: true
    description:
      type: varchar(255)

Faq:
  connection: doctrine
  tableName: faq
  columns:
    id_faq:
      type: integer(8)
      primary: true
      autoincrement: true
      notnull: true
    request:
      type: text
      notnull: true
    answer:
      type: text
      notnull: true
    status:
      type: integer(2)
      notnull: true
    position:
      type: integer(8)
      notnull: true

FileType:
  connection: doctrine
  tableName: file_type
  actAs:
    Timestampable: ~
    Sluggable:
      fields: [name]
  columns:
    id_file_type:
      type: integer(8)
      primary: true
      autoincrement: true
    name:
      type: varchar(50)
      notnull: true
    description:
      type: text

FileCategory:
  connection: doctrine
  tableName: file_category
  actAs:
    Timestampable: ~
    Sluggable:
      fields: [name]
  columns:
    id_file_category:
      type: integer(8)
      primary: true
      autoincrement: true
    name:
      type: varchar(50)
      notnull: true
    description:
      type: text

File:
  connection: doctrine
  tableName: file
  actAs:
    Timestampable: ~
    Sluggable:
      fields: [name]
  columns:
    id_file:
      type: integer(8)
      primary: true
      autoincrement: true
    name:
      type: varchar(50)
      notnull: true
    file:
      type: text
      notnull: true
    description:
      type: text
    file_type_id:
      type: integer(8)
    file_category_id:
      type: integer(8)
    position:
      type: integer(8)
    status:
      type: integer(2)
  relations:
    FileType:
      local: file_type_id
      foreign: id_file_type
      type: one
    FileCategory:
      local: file_category_id
      foreign: id_file_category
      type: one

Entree:
  connection: doctrine
  tableName: entree
  actAs:
    Timestampable: ~
  columns:
    id_entree:
      type: integer(4)
      primary: true
      autoincrement: true
    user_id:
      type: integer(8)
      notnull: true
    is_enter:
      type: integer(4)
      notnull: false
      default: 0
    is_prepayed:
      type: integer(4)
      notnull: false
      default: 0
    payement_amount:
      type: integer(4)
      notnull: false
    payement_type:
      type: integer(4)
      notnull: false
    parental_consent:
      type: integer(4)
      notnull: true
      default: 0
    created_by:
      type: integer(8)
      notnull: true

Gallery:
  connection: doctrine
  tableName: gallery
  actAs:
    Timestampable: ~
    Sluggable:
      fields: [title]
  columns:
    id_gallery:
      type: integer(4)
      primary: true
      autoincrement: true
    title:
      type: string(255)
      notnull: false
    album_id:
      type: string(50)
      notnull: true
    description:
      type: string(255)
      notnull: false
    position:
      type: integer(4)
      notnull: true
      default: 99
    status:
      type: boolean
      default: false

SfGuardUserProfile:
  connection: doctrine
  tableName: sf_guard_user_profile
  columns:
    user_id:
      type: integer(8)
      primary: true
      notnull: true
    ean13:
      type: string(13)
      notnull: true
    phone:
      type: string(20)
      notnull: false
    birthdate:
      type: date
      notnull: false
    gender:
      type: enum
      values: [unknow, female, male]
      default: unknow
    website:
      type: string(250)
      notnull: false
    logourl:
      type: string(250)
      notnull: false
    carrer:
      type: string()
      notnull: false
  relations:
    SfGuardUser:
      class: sfGuardUser
      local: user_id
      foreign: id
      type: one
      foreignType: one

SfGuardUserLicenceMasters:
  connection: doctrine
  tableName: sf_guard_user_licence_masters
  columns:
    user_id:
      type: integer(8)
      notnull: true
      primary: true
    type:
      type: string(15)
      notnull: false
    serial:
      type: string(40)
      notnull: true
    season:
      type: string(9)
      notnull: false
    username:
      type: string(50)
      notnull: false
    used:
      type: integer(4)
      notnull: false
  relations:
    SfGuardUser:
      class: sfGuardUser
      local: user_id
      foreign: id
      type: one
      foreignType: one

SfGuardUserAddress:
  connection: doctrine
  tableName: sf_guard_user_address
  columns:
    id:
      type: integer(8)
      primary: true
      autoincrement: true
    user_id:
      type: integer(8)
      notnull: true
    name:
      type: string(50)
      notnull: true
    complement:
      type: string(50)
      notnull: false
    address:
      type: string()
      notnull: true
    zipcode:
      type: string(10)
      notnull: true
    city:
      type: string(50)
      notnull: true
    country:
      type: string(50)
      notnull: true
    latitude:
      type: string(20)
      notnull: false
    longitude:
      type: string(20)
      notnull: false
    is_default:
      type: boolean
      default: false
    is_billing:
      type: boolean
      default: false
    is_delivery:
      type: boolean
      default: false

  relations:
    SfGuardUser:
      class: sfGuardUser
      local: user_id
      foreign: id
      type: one

SfGuardUserTshirt:
  connection: doctrine
  tableName: sf_guard_user_tshirt
  columns:
    user_id:
      type: integer(8)
      notnull: true
      primary: true
    size:
      type: enum
      values: [XS, S, M, L, XL, XXL, XXXL]
      default: M
  relations:
    SfGuardUser:
      class: sfGuardUser
      local: user_id
      foreign: id
      type: one
      foreignType: one

SfGuardUserWeezevent:
  connection: doctrine
  tableName: sf_guard_user_weezevent
  columns:
    user_id:
      type: integer(8)
      notnull: true
      primary: true
    event_id:
      type: string(50)
      notnull: false
    tournament_id:
      type: string(50)
      notnull: false
    barcode:
      type: string(50)
      notnull: true
      unique : true
    is_valid:
      type: boolean
      default: false
  relations:
    SfGuardUser:
      class: sfGuardUser
      local: user_id
      foreign: id
      type: one
      foreignType: one
